name: Check trigger release

on:
  workflow_call:
    inputs:
      plugin:
        type: string

jobs:
  release:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{inputs.plugin}}-${{matrix.os}}-python-${{matrix.python-version}}
          restore-keys: ${{inputs.plugin}}
      - name: Install dependencies
        run: |
            cd ${{ inputs.plugin }}
            pip install git+https://github.com/kedro-org/kedro@main
            pip install -r test_requirements.txt
            pip freeze
      - name: Install pre-commit hooks
        run: |
            cd ${{ inputs.plugin }}
            pre-commit install --install-hooks
            pre-commit install --hook-type pre-push
      - name: Run linter
        run: make plugin=${{ inputs.plugin }} lint
