name: Release

on:
  workflow_call:
    inputs:
      plugin:
        type: string
      package_name:
        type: string
      package_version:
        type: string

jobs:
  test:
    uses: ./.github/workflows/check-plugin.yml
    with:
      plugin: ${{ inputs.plugin }}

  build and release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests build

      - name: Build package
          run: make package PLUGIN=${{ inputs.plugin }}

    - name: Create GitHub Release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_TAGGING_TOKEN }}
        script: |
          const package_name = "${{ inputs.package_name }}"
          const package_version = "${{ inputs.package_version }}"
          const response = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `${{ inputs.package_name }}-${{ inputs.package_version }}`,
            target_commitish: 'main',
            name: `${{ inputs.package_name }}-${{ inputs.package_version }}`,
            body: `Release ${package_version}`,
            draft: false,
            prerelease: false,
          });
          return response.data;

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ${{ inputs.package_name }}/dist
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
